app	<Alt>F3	xfce4-appfinder
app	<Super>4	libreoffice --calc
app	<Alt>F1	xfce4-popup-applicationsmenu
app	<Super>1	parole
app	<Super>3	libreoffice --writer
app	<Super>v	/usr/share/code/code --unity-launch
app	<Primary><Alt>v	/usr/share/code/code --unity-launch
app	<Primary><Alt>4	xfce4-screenshooter -r
app	<Super>o	xfce4-popup-whiskermenu
app	<Primary><Alt>k	kitty
window	<Primary><Alt>l	tile_right
window	<Primary><Alt>j	tile_left
window	<Primary><Alt>u	tile_up_left
window	<Primary><Alt>o	tile_up_right
window	<Primary><Alt>n	tile_down_left
window	<Primary><Alt>period	tile_down_right
window	<Primary><Alt>m	maximize_window
window	<Primary><Shift>Right	move_window_next_workspace
window	<Primary><Shift>Left	move_window_prev_workspace
app	<Primary><Alt>Delete	xflock4
app	<Primary><Alt>t	alacritty
app	<Super>e	mousepad
app	<Super>r	xfce4-appfinder
app	XF86Music	parole
window	<Primary><Alt>Right	next_workspace
window	<Primary><Alt>Left	prev_workspace
